server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
        - id: reservation-service
          uri: http://localhost:8082
          predicates:
                - Path=/api/v1/payments/**,/api/v1/reservations/**
        - id: room-service
          uri: http://localhost:8083
          predicates:
                - Path=/api/v1/room/**

rsa:
    public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework.cloud.gateway: DEBUG
      org.springframework.security: DEBUG
      root: INFO
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG

  file:
    name: gateway.log
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"